<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" ignored="1" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="5494" started-at="2020-04-22T20:49:33Z" finished-at="2020-04-22T20:49:39Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="5494" started-at="2020-04-22T20:49:33Z" finished-at="2020-04-22T20:49:39Z">
      <class name="com.swetha.testcases.AddCustomerTest">
        <test-method status="SKIP" signature="addCustomer(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.swetha.testcases.AddCustomerTest@52350abb]" name="addCustomer" duration-ms="0" started-at="2020-04-23T02:19:39Z" data-provider="getData" finished-at="2020-04-23T02:19:39Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 3]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 3
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:115)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:509)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1308)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1036)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1126)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3
	at com.swetha.testcases.AddCustomerTest.getData(AddCustomerTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:55)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
	... 22 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addCustomer -->
      </class> <!-- com.swetha.testcases.AddCustomerTest -->
      <class name="com.swetha.testcases.BankManagerLoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.swetha.testcases.BankManagerLoginTest@cc6460c]" name="setUp" is-config="true" duration-ms="20104" started-at="2020-04-23T02:19:13Z" finished-at="2020-04-23T02:19:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="loginAsBankManager()[pri:0, instance:com.swetha.testcases.BankManagerLoginTest@cc6460c]" name="loginAsBankManager" duration-ms="3334" started-at="2020-04-23T02:19:33Z" finished-at="2020-04-23T02:19:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.swetha.testcases.BankManagerLoginTest@cc6460c]" name="tearDown" is-config="true" duration-ms="1180" started-at="2020-04-23T02:19:39Z" finished-at="2020-04-23T02:19:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.swetha.testcases.BankManagerLoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
